### ISSUE TITLE
Symfony7, PHP 8.3

### ISSUE THREAD

**Issue by hovorma** [jbouzekri/PhumborBundle#24]
Hello, I am using actively using your bundle in my projects. Currently, I am working with Symfony 7 with PHP 8.3, it seems the bundle is not compatible yet with them, are you going to update it?

**Comment by hovorma** [comment]
hi @jbouzekri, thanks a lot for your answer. It gives an error in the bundle configuration tree. maybe Symfony changed a bit structure of the configs.

**Comment by jbouzekri** [comment]
@hovorma : can you post the exception please ?

**Comment by hovorma** [comment]
![image](https://github.com/jbouzekri/PhumborBundle/assets/38100705/897c9e05-ffe8-4187-8b75-d56c3e4763c7)

sure, after the "composer require" of your bundle, during cache:clear I get this error

**Comment by jbouzekri** [comment]
@hovorma  : can you test the branch https://github.com/jbouzekri/PhumborBundle/tree/feat-sf7 ? If it works for you, I will merge it and tag a new release.

**Comment by jbouzekri** [comment]
Thanks @FabianSchmick

@hovorma : 3.2.0 version released with the #25 MR.
